<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Viocon' => array($vendorDir . '/usmanhalalit/viocon/src'),
    'Symfony\\Component\\Routing\\' => array($vendorDir . '/symfony/routing'),
    'Symfony\\Component\\HttpFoundation\\' => array($vendorDir . '/symfony/http-foundation'),
    'Symfony\\Component\\EventDispatcher\\' => array($vendorDir . '/symfony/event-dispatcher'),
    'Rev' => array($baseDir . '/'),
    'Ratchet' => array($vendorDir . '/cboden/ratchet/src'),
    'Pixie' => array($vendorDir . '/usmanhalalit/pixie/src'),
    'Mustache' => array($vendorDir . '/mustache/mustache/src'),
    'Kryptos\\Handler' => array($vendorDir . '/kryptos/errorhandler'),
    'Guzzle\\Stream' => array($vendorDir . '/guzzle/stream'),
    'Guzzle\\Parser' => array($vendorDir . '/guzzle/parser'),
    'Guzzle\\Http' => array($vendorDir . '/guzzle/http'),
    'Guzzle\\Common' => array($vendorDir . '/guzzle/common'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
);
